Repository boostcampwm-2021/web03-boocamWiki, pull requests merged in 2021-12, with the labels that each got.

#164 test, refactor : 문서열람 테스트 및 리팩토링. React-Markdown Mock 검사
  client/.eslintrc.js
  client/package-lock.json
  client/package.json
  client/src/App.test.tsx
  client/src/components/common/MdParser.test.jsx
  client/src/components/common/WikiContentsIndex.jsx
  client/src/components/make-section/MakeSection.jsx
  client/src/components/make-section/UpdateSection.jsx
  client/src/components/make-section/make-section-components/DocCard.jsx
  client/src/components/make-section/make-section-components/InputTitle.jsx
  client/src/components/wiki-section/WikiSection.tsx
  client/src/components/wiki-section/wiki-section-components/WikiCard.test.jsx
  client/src/components/wiki-section/wiki-section-components/WikiCard.tsx
  client/src/components/wiki-section/wiki-section-components/WikiCategory.test.jsx
  client/src/components/wiki-section/wiki-section-components/WikiCategory.tsx
  client/src/reducer/doc-data-reducer.ts
  client/src/styles/styled-components/mixin.ts
Labels: 🪲 QBug, 🛠 fix

#165 feat: 수정 시, 뒤로가기 시 Confirm 창 구현, 기여도 데이터 받아오는 로직 추가
  client/src/App.tsx
  client/src/components/alert-confirm/AlertConfirm.jsx
  client/src/components/make-section/MakeSection.jsx
  client/src/components/make-section/UpdateSection.jsx
  client/src/components/make-section/make-section-components/Editor.jsx
  client/src/components/make-section/make-section-components/EditorBox.jsx
  client/src/components/make-section/make-section-components/EditorWithPreview.jsx
  client/src/components/rank-section/RankSection.jsx
  client/src/components/rank-section/rank-components/ContributionRank.jsx
  client/tsconfig.json
  server/src/api/rank.ts
  server/src/sql/rank-query.ts
Labels: 🧑🏻‍💻 front, 👨🏻‍💻 backend

#169 hotfix : 분류페이지 네비게이션 정상동작안함 처리
  client/src/components/category-section/CategorySection.jsx
Labels: 🪲 QBug, 🧑🏻‍💻 front, 🛠 fix

#170 [depoloy3-1] 최종배포
  client/src/components/category-section/CategorySection.jsx
Labels: 🛠 fix

#171 fix : 분류페이지에서 offset에 대한 api 쿼리 없는 현상 수정
  client/src/components/category-section/CategorySection.jsx
Labels: 🪲 QBug, 🧑🏻‍💻 front, 🛠 fix

#172 [DEPOY5] hotfix배포
  client/src/components/category-section/CategorySection.jsx
Labels: 🪲 QBug, 🧑🏻‍💻 front, 🛠 fix
