Repository boostcampwm-2021/web03-boocamWiki, pull requests merged in 2021-11, with the labels that each got.

#3 이슈 템플릿 업데이트
  .github/ISSUE_TEMPLATE/-------.md
Labels: 💫 chore

#5 [Chore] 이슈템플릿 생성
  .github/ISSUE_TEMPLATE/-------.md
Labels: 💫 chore

#4 [chore] 개발 환경 세팅
  .git-message.txt
  .gitignore
  client/.eslintrc.js
  client/.gitignore
  client/.prettierrc
  client/README.md
  client/package-lock.json
  client/package.json
  client/public/favicon.ico
  client/public/index.html
  client/public/logo192.png
  client/public/logo512.png
  client/public/manifest.json
  client/public/robots.txt
  client/src/App.css
  client/src/App.test.tsx
  client/src/App.tsx
  client/src/index.css
  client/src/index.tsx
  client/src/logo.svg
  client/src/react-app-env.d.ts
  client/src/reportWebVitals.ts
  client/src/setupTests.ts
  client/tsconfig.json
  server/.eslintrc.js
  server/.prettierrc
  server/package-lock.json
  server/package.json
  server/src/app.ts
  server/src/loaders/express.ts
  server/src/loaders/index.ts
  server/tsconfig.json
Labels: 💫 chore, 🧑🏻‍💻 front, 👨🏻‍💻 backend

#10 feat: 기본 레이아웃 구현
  client/.eslintrc.js
  client/package-lock.json
  client/package.json
  client/src/App.css
  client/src/App.tsx
  client/src/header/Header.jsx
  client/src/header/HeaderMenu.jsx
  client/src/header/HeaderSearchBar.jsx
  client/src/header/HeaderUser.jsx
  client/src/header/Logo.jsx
  client/src/resource/img/logo.png
  client/src/resource/img/map.svg
  client/src/resource/img/rank.svg
  client/src/resource/img/recent.svg
  client/src/resource/img/search.svg
  client/src/resource/img/user.svg
  client/src/section/Section.jsx
  client/src/section/mainpage/mainHeader.jsx
  client/src/section/mainpage/mainSection.jsx
  client/src/section/sidepage/rankSection.jsx
  client/src/section/sidepage/recentSection.jsx
  client/src/section/sidepage/sideHeader.jsx
Labels: 🧑🏻‍💻 front

#30 feat: 메인페이지 레이아웃 수정
  client/src/header/Header.jsx
  client/src/section/Section.jsx
  client/src/section/mainpage/mainSection.jsx
  client/src/section/sidepage/rankSection.jsx
  client/src/section/sidepage/recentSection.jsx
Labels: 🧑🏻‍💻 front

#31 chore: express bulletproof 아키텍쳐 구현
  server/src/config/index.ts
  server/src/jobs/crontab.sh
  server/src/models/index.ts
  server/src/services/index.ts
  server/src/subscribers/index.ts
  server/src/types/d.ts
Labels: 👨🏻‍💻 backend, priority: 크리티컬 🔥🔥🔥

#32 chore: server 내 api 폴더 생성
  server/src/api/documents.ts
Labels: 💫 chore, 👨🏻‍💻 backend, priority: 크리티컬 🔥🔥🔥

#33 feat: 리액트 라우터 적용
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/components/Main.jsx
  client/src/components/header/Header.jsx
  client/src/components/header/HeaderMenu.jsx
  client/src/components/header/HeaderSearchBar.jsx
  client/src/components/header/HeaderUser.jsx
  client/src/components/header/Logo.jsx
  client/src/components/section/Section.jsx
  client/src/components/section/mainpage/mainHeader.jsx
  client/src/components/section/mainpage/mainSection.jsx
  client/src/components/section/makepage/mainHeader.jsx
  client/src/components/section/makepage/mainSection.jsx
  client/src/components/section/sidepage/rankSection.jsx
  client/src/components/section/sidepage/recentSection.jsx
  client/src/components/section/sidepage/sideHeader.jsx
  client/src/components/section/tmpPage/mainHeader.jsx
  client/src/components/section/tmpPage/mainSection.jsx
  client/src/index.tsx
Labels: 🧑🏻‍💻 front

#34 feat : mysql2, env 종속성 추가
  package-lock.json
  server/.env.example
  server/package-lock.json
  server/package.json
  server/src/app.ts
  server/src/config/index.ts
  server/src/loaders/index.ts
  server/src/loaders/mysql.ts
Labels: 💫 chore, 👨🏻‍💻 backend

#36 feat: search api 생성
  server/package-lock.json
  server/package.json
  server/src/api/documents.ts
  server/src/sql/documents-query.ts
  server/src/types/apiInterface.ts
Labels: 👨🏻‍💻 backend, priority: 중요, 문서작성

#37 feat: prettier 적용, api route (생성, 순위)
  server/src/api/documents.ts
  server/src/api/index.ts
  server/src/loaders/index.ts
  server/src/loaders/mysql.ts
  server/src/services/db-pool.ts
  server/src/sql/documents-query.ts
Labels: 👨🏻‍💻 backend

#39 feat: 문서 작성 페이지 제목 중복 체크 기능 구현
  client/.eslintrc.js
  client/src/components/make-section/MakeSection.jsx
  client/src/components/make-section/make-section-components/InputTitle.jsx
Labels: 🧑🏻‍💻 front

#41 feat: 문서 작성 구현
  client/src/components/make-section/MakeSection.jsx
  client/src/components/make-section/make-section-components/InputTitle.jsx
  server/src/loaders/express.ts
Labels: 🧑🏻‍💻 front, 👨🏻‍💻 backend

#40 fix: client 내 .eslintrc.js 수정
  client/.eslintrc.js
Labels: 🛠 fix

#44 feat: 문서 생성 API 구현
  client/src/components/make-section/MakeSection.jsx
  client/src/pages/makePage.jsx
  server/package-lock.json
  server/src/sql/documents-query.ts
Labels: 🧑🏻‍💻 front, 👨🏻‍💻 backend

#45 feat: 패스워드 생성 함수 추가
  server/package-lock.json
  server/package.json
  server/src/api/documents.ts
  server/src/services/login.ts
Labels: 👨🏻‍💻 backend

#46 fix: API user_id 오류, 문서 열람 오류 수정
  .vscode/settings.json
  client/src/components/main-section/MainSection.jsx
  client/src/components/main-section/temp.txt
  client/src/components/make-section/MakeSection.jsx
  server/package-lock.json
  server/src/api/documents.ts
  server/src/sql/documents-query.ts
Labels: 🛠 fix

#47 feat : 최근 변경 문서 사항 기능 구성
  client/src/components/side-section/SideSection.jsx
  client/src/components/side-section/side-section-components/SectionItem.jsx
  server/src/api/documents.ts
  server/src/sql/documents-query.ts
Labels: 🧑🏻‍💻 front, 👨🏻‍💻 backend, 🛠 fix

#48 fix: 변경 사항 순위 시간순서로 변경
  server/src/sql/documents-query.ts
Labels: 🛠 fix

#61 feat: search API content 추가
  server/src/api/documents.ts
  server/src/sql/documents-query.ts
  server/src/types/apiInterface.ts
Labels: 👨🏻‍💻 backend, 문서검색

#62 feat, refactor 분류 상태 추가, 분류 상태를 위한 리팩토링 진행
  client/src/components/make-section/MakeSection.jsx
  client/src/components/make-section/make-section-components/Editor.jsx
  client/src/components/make-section/make-section-components/EditorWithPreview.jsx
  client/src/components/make-section/make-section-components/InputTitle.jsx
  client/src/components/make-section/make-section-components/Preview.jsx
Labels: 🧑🏻‍💻 front, 🛠 fix

#63 feat: 문서 작성시 부캠위키의 규정을 제공
  client/src/components/make-section/MakeSection.jsx
  client/src/components/make-section/make-section-components/EditorWithPreview.jsx
  client/src/components/make-section/make-section-components/MakePageRule.jsx
  client/src/components/make-section/make-section-components/Preview.jsx
  client/src/components/make-section/make-section-components/ruleText.js
Labels: 🧑🏻‍💻 front, 🛠 fix

#65 fix: 문서 생성 분류 버그 수정
  client/src/components/make-section/make-section-components/InputTitle.jsx
Labels: 🧑🏻‍💻 front, 🛠 fix

#66 feat: 문서 명함 기능 구현
  client/src/components/make-section/MakeSection.jsx
  client/src/components/make-section/make-section-components/DocCard.jsx
Labels: 🧑🏻‍💻 front

#68 feat: search API 변경 및 search 페이지 리다이렉트 구현
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/components/header/header-components/HeaderSearchBar.jsx
  client/src/components/header/header-components/Logo.jsx
  client/src/components/search-section/SearchSecion.jsx
  client/src/pages/ErrorPage.jsx
  client/src/pages/SearchPage.jsx
  server/src/api/documents.ts
  server/src/sql/documents-query.ts
  server/src/types/apiInterface.ts
Labels: 🧑🏻‍💻 front, 👨🏻‍💻 backend, GNB, 문서검색

#69 fix: Search 페이지 내 검색 미동작 오류 해결
  client/src/components/search-section/SearchSecion.jsx
Labels: 🧑🏻‍💻 front, 🛠 fix, 문서검색

#71 feat: 문서 생성 페이지 레이아웃 구성
  client/src/components/make-section/MakeSection.jsx
  client/src/components/make-section/make-section-components/DocCard.jsx
  client/src/components/make-section/make-section-components/DocCardPreview.jsx
  client/src/components/make-section/make-section-components/Editor.jsx
  client/src/components/make-section/make-section-components/EditorWithPreview.jsx
  client/src/components/make-section/make-section-components/InputTitle.jsx
  client/src/components/make-section/make-section-components/MakePageRule.jsx
  client/src/components/make-section/make-section-components/MarkdownPreview.jsx
  client/src/components/make-section/make-section-components/Preview.jsx
Labels: 🧑🏻‍💻 front

#72 style: 문서 작성 페이지 명함 입력 양식 스타일 변경
  client/src/components/header/Header.jsx
  client/src/components/header/header-components/HeaderMenu.jsx
  client/src/components/make-section/make-section-components/DocCard.jsx
Labels: 🧑🏻‍💻 front

#73 feat: 검색결과 페이지 생성
  client/package-lock.json
  client/package.json
  client/src/components/search-section/SearchSection.jsx
  client/src/components/search-section/search-section-components/ResultContent.jsx
  client/src/components/search-section/search-section-components/ResultFooter.jsx
  client/src/components/search-section/search-section-components/ResultSummary.jsx
  client/src/components/search-section/search-section-components/ResultView.jsx
  client/src/pages/MainPage.jsx
  client/src/pages/MakePage.jsx
  client/src/pages/SearchPage.jsx
  client/src/pages/WikiPage.jsx
Labels: 🧑🏻‍💻 front, 🛠 fix, 문서검색

#76 Feature/front j138
  client/src/components/make-section/MakeSection.jsx
  client/src/components/make-section/make-section-components/DocCard.jsx
  client/src/components/make-section/make-section-components/DocCardPreview.jsx
  client/src/components/make-section/make-section-components/InputTitle.jsx
  client/src/resource/img/genDownBtn.svg
  client/src/resource/img/genUpBtn.svg
  client/src/resource/img/no-image.png
Labels: 🧑🏻‍💻 front, 🛠 fix

#77 feat/refactor: scss 리팩토링, 헤더 검색 타입 레이아웃 추가
  client/src/App.css
  client/src/App.tsx
  client/src/components/Loading.jsx
  client/src/components/MdParser.jsx
  client/src/components/header/Header.jsx
  client/src/components/header/header-components/HeaderMenu.jsx
  client/src/components/header/header-components/HeaderSearchBar.jsx
  client/src/components/header/header-components/HeaderUser.jsx
  client/src/components/header/header-components/Logo.jsx
  client/src/components/main-section/MainSection.jsx
  client/src/components/make-section/MakeSection.jsx
  client/src/components/side-section/side-section-components/SectionItem.jsx
  client/src/index.css
  client/src/index.tsx
  client/src/pages/ErrorPage.jsx
  client/src/pages/MainPage.jsx
  client/src/pages/MakePage.jsx
  client/src/pages/SearchPage.jsx
  client/src/pages/WikiPage.jsx
  client/src/resource/img/drop.svg
  client/src/resource/img/logo2.png
  client/src/styles/MdParser.module.scss
  client/src/styles/global.scss
  client/src/styles/makePage.module.scss
  client/src/styles/scss/ErrorPage.module.scss
  client/src/styles/scss/Page.module.scss
  client/src/styles/scss/global.scss
  client/src/styles/scss/index.scss
Labels: 🧑🏻‍💻 front, 🛠 fix

#78 feat: 검색결과 페이지 레이아웃 및 API 추가
  client/src/components/header/header-components/HeaderSearchBar.jsx
  client/src/components/search-section/SearchSection.jsx
  client/src/components/search-section/search-section-components/ResultContent.jsx
  client/src/components/search-section/search-section-components/ResultFooter.jsx
  client/src/components/search-section/search-section-components/ResultSummary.jsx
  client/src/components/search-section/search-section-components/ResultView.jsx
  server/src/api/documents.ts
  server/src/sql/documents-query.ts
Labels: 🧑🏻‍💻 front, 👨🏻‍💻 backend, 문서검색

#80 Feature/front j138
  client/src/components/make-section/MakeSection.jsx
  client/src/components/make-section/make-section-components/DocCard.jsx
  client/src/components/wiki-section/WikiSection.jsx
Labels: 🧑🏻‍💻 front, 🛠 fix

#84 Feature/front j138
  client/src/components/make-section/MakeSection.jsx
  client/src/components/make-section/make-section-components/DocCard.jsx
  client/src/components/make-section/make-section-components/Editor.jsx
  client/src/components/make-section/make-section-components/EditorBox.jsx
  client/src/components/make-section/make-section-components/InputTitle.jsx
  client/src/components/make-section/make-section-components/MakePageRule.jsx
Labels: 🧑🏻‍💻 front

#85 style: 문서 작성 페이지, 에디터 레이아웃 변경
  client/src/components/make-section/MakeSection.jsx
  client/src/components/make-section/make-section-components/DocCard.jsx
  client/src/components/make-section/make-section-components/Editor.jsx
  client/src/components/make-section/make-section-components/EditorBox.jsx
  client/src/components/make-section/make-section-components/EditorWithPreview.jsx
  client/src/components/make-section/make-section-components/InputTitle.jsx
  client/src/components/make-section/make-section-components/Preview.jsx
Labels: 🧑🏻‍💻 front

#86 feat: 내용 검색 시 highlight 및 검색 페이지 footer 수정
  client/src/components/search-section/search-section-components/ResultContent.jsx
  client/src/components/search-section/search-section-components/ResultFooter.jsx
  client/src/components/search-section/search-section-components/ResultSummary.jsx
  client/src/components/search-section/search-section-components/ResultView.jsx
  client/src/components/side-section/side-section-components/SectionItem.jsx
  client/src/components/side-section/side-section-components/SectionListGenerator.tsx
  client/src/components/side-section/side-section-components/recents/RecentItem.tsx
  client/src/components/side-section/side-section-components/top-views/TopViewItem.tsx
  client/src/components/wiki-section/WikiSection.jsx
  client/src/pages/WikiPage.jsx
  client/src/types/api-document.ts
  client/src/utils/documents.js
Labels: 🧑🏻‍💻 front, 🛠 fix, 문서검색

#87 fix: 검색 결과 페이지 이동 버튼 크기 수정
  client/src/components/search-section/search-section-components/ResultFooter.jsx
Labels: 🧑🏻‍💻 front, 🛠 fix, 문서검색

#88 feat: 문서 열람 페이지 명함 구현, input placeholder 내용 제거 구현
  client/src/components/SectionTitle.jsx
  client/src/components/main-section/MainSection.jsx
  client/src/components/make-section/make-section-components/DocCard.jsx
  client/src/components/make-section/make-section-components/InputTitle.jsx
  client/src/components/wiki-section/WikiSection.jsx
  client/src/components/wiki-section/wiki-section-components/WikiCard.jsx
Labels: 🧑🏻‍💻 front, 🛠 fix

#89 fix: 검색 페이지 오류 수정
  client/src/components/search-section/SearchSection.jsx
  client/src/components/search-section/search-section-components/ResultFooter.jsx
Labels: 🧑🏻‍💻 front, 🛠 fix, 문서검색

#90 feat: modal 컴포넌트 추가, 검색 모달 추가, 유저 모달 추가
  client/src/components/header/header-components/HeaderSearchBar.jsx
  client/src/components/header/header-components/HeaderUser.jsx
  client/src/components/select-modal/SelectModal.jsx
  client/src/pages/MainPage.jsx
Labels: 🧑🏻‍💻 front, GNB

#91 fix: placeholder 내용 변경
  client/src/components/make-section/make-section-components/InputTitle.jsx
Labels: 🛠 fix

#92 Feat: custom-select 생성, 헤더&메인 반응형 UI 구현, CSS 디자인 및 버그 수정
  client/.eslintrc.js
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/components/SectionTitle.jsx
  client/src/components/header/Header.jsx
  client/src/components/header/header-components/HeaderMenu.jsx
  client/src/components/header/header-components/HeaderSearchBar.jsx
  client/src/components/header/header-components/HeaderUser.jsx
  client/src/components/header/header-components/Logo.jsx
  client/src/components/main-section/MainSection.jsx
  client/src/components/make-section/MakeSection.jsx
  client/src/components/make-section/make-section-components/Editor.jsx
  client/src/components/make-section/make-section-components/EditorBox.jsx
  client/src/components/make-section/make-section-components/EditorWithPreview.jsx
  client/src/components/make-section/make-section-components/InputTitle.jsx
  client/src/components/make-section/make-section-components/WikiContentsIndex.jsx
  client/src/components/select-modal/SelectModal.jsx
  client/src/components/side-section/SideSection.jsx
  client/src/components/side-section/side-section-components/SectionItem.jsx
  client/src/components/side-section/side-section-components/SectionListGenerator.tsx
  client/src/components/side-section/side-section-components/recents/RecentItem.tsx
  client/src/components/side-section/side-section-components/top-views/TopViewItem.tsx
  client/src/components/wiki-section/WikiSection.jsx
  client/src/event-handler/select-handler.ts
  client/src/magic-number.ts
  client/src/reducer/doc-data-reducer.ts
  client/src/reducer/select-toggle-reducer.ts
  client/src/reducer/select-type-reducer.ts
  client/src/styles/scss/ErrorPage.module.scss
Labels: 🧑🏻‍💻 front

#99 feat: 문서 수정 기능 구현
  client/src/App.tsx
  client/src/components/make-section/UpdateSection.jsx
  client/src/components/make-section/make-section-components/DocCard.jsx
  client/src/components/wiki-section/WikiSection.jsx
  client/src/pages/UpdatePage.jsx
  client/src/reducer/doc-data-reducer.ts
  server/src/api/documents.ts
  server/src/sql/documents-query.ts
Labels: 🧑🏻‍💻 front, 👨🏻‍💻 backend

#100 refactor: server 라우터 및 api 코드 수정
  server/.eslintrc.js
  server/package-lock.json
  server/package.json
  server/src/api/documents.ts
  server/src/sql/documents-query.ts
  server/src/types/apiInterface.ts
Labels: 👨🏻‍💻 backend

#101 Feature/front j138
  client/src/components/make-section/UpdateSection.jsx
  client/src/components/make-section/make-section-components/DocCard.jsx
  client/src/components/make-section/make-section-components/Editor.jsx
  client/src/components/make-section/make-section-components/EditorWithPreview.jsx
  client/src/components/make-section/make-section-components/InputTitle.jsx
  client/src/components/make-section/make-section-components/input-title-components/BoostCampId.jsx
  client/src/components/make-section/make-section-components/input-title-components/Classification.jsx
  client/src/components/make-section/make-section-components/input-title-components/CreateBtn.jsx
  client/src/components/make-section/make-section-components/input-title-components/DocName.jsx
  client/src/components/make-section/make-section-components/input-title-components/Generation.jsx
  client/src/components/make-section/make-section-components/input-title-components/style.js
  client/src/reducer/doc-data-reducer.ts
  server/src/api/documents.ts
  server/src/sql/documents-query.ts
Labels: 🧑🏻‍💻 front, 🛠 fix

#102 Feature/#57 j187
  client/src/components/SectionTitle.jsx
  client/src/components/common/Loading.jsx
  client/src/components/common/MainSection.jsx
  client/src/components/common/MdParser.jsx
  client/src/components/common/SectionTitle.jsx
  client/src/components/main-door/MainDoor.jsx
  client/src/components/make-section/make-section-components/EditorWithPreview.jsx
  client/src/components/make-section/make-section-components/MakePageRule.jsx
  client/src/components/make-section/make-section-components/Preview.jsx
  client/src/components/make-section/make-section-components/WikiContentsIndex.jsx
  client/src/components/search-section/SearchSection.jsx
  client/src/components/wiki-section/WikiSection.jsx
  client/src/components/wiki-section/wiki-section-components/WikiCategory.jsx
  client/src/pages/WikiPage.jsx
Labels: 🧑🏻‍💻 front

#103 fix: 서버 코드 리팩토링 후 일어난 사이드 이펙트 제거
  client/src/components/search-section/SearchSection.jsx
  client/src/components/side-section/side-section-components/SectionItem.jsx
Labels: 🧑🏻‍💻 front, 👨🏻‍💻 backend, 🛠 fix

#105 feat: 문서 작성 제목 부분 반응형 쿼리 적용
  client/src/components/make-section/make-section-components/InputTitle.jsx
  client/src/components/make-section/make-section-components/input-title-components/Classification.jsx
  client/src/components/make-section/make-section-components/input-title-components/style.js
Labels: 🧑🏻‍💻 front

#111 chore: 도커 관련 세팅
  client/src/components/main-door/MainDoor.jsx
  client/src/components/make-section/MakeSection.jsx
  client/src/components/make-section/UpdateSection.jsx
  client/src/components/make-section/make-section-components/InputTitle.jsx
  client/src/components/search-section/SearchSection.jsx
  client/src/components/side-section/side-section-components/recents/RecentItem.tsx
  client/src/components/side-section/side-section-components/top-views/TopViewItem.tsx
  client/src/components/wiki-section/WikiSection.jsx
  docker/config.sh
  docker/docker-compose.yml
  docker/nginx/build/index.html
  docker/nginx/nginx/conf.d/default.conf
  docker/nginx/nginx/fastcgi_params
  docker/nginx/nginx/mime.types
  docker/nginx/nginx/nginx.conf
  docker/nginx/nginx/scgi_params
  docker/nginx/nginx/uwsgi_params
  server/package-lock.json
  server/package.json
  server/src/loaders/express.ts
Labels: 💫 chore, 아키텍쳐&CI/CD

#112 feat: 이미지 추가 기능 구현
  .vscode/settings.json
  client/src/components/make-section/make-section-components/DocCard.jsx
  client/src/components/make-section/make-section-components/Editor.jsx
  client/src/components/make-section/make-section-components/EditorBox.jsx
  client/src/components/make-section/make-section-components/EditorWithPreview.jsx
  server/.env.example
  server/package-lock.json
  server/package.json
  server/src/api/images.ts
  server/src/api/index.ts
  server/src/config/index.ts
Labels: 🧑🏻‍💻 front, 👨🏻‍💻 backend

#113 chore: 도커 환경설정 수정
  client/package.json
  docker/config.sh
  docker/docker-compose.yml
  docker/nginx/nginx/conf.d/default.conf
  server/package.json
Labels: 💫 chore, 아키텍쳐&CI/CD

#115 chore: nginx 환경 설정 변경
  client/package-lock.json
  client/package.json
  docker/nginx/nginx/conf.d/default.conf
Labels: 💫 chore, 아키텍쳐&CI/CD

#116 feat: github-action script 작성
  .github/workflows/deploy.yml
Labels: 아키텍쳐&CI/CD

#117 chore: package.json postbuild 스크립트 수정
  client/package.json
  docker/nginx/build/index.html
  server/package.json
Labels: 💫 chore

#118 hotfix: 열람페이지서 모바일뷰 대응
  client/src/components/wiki-section/WikiSection.jsx
Labels: 🪲 QBug, 🛠 fix

#120 ci/cd test
  .github/workflows/deploy.yml
  .gitignore
  .vscode/settings.json
  docker/docker-compose.yml
Labels: 아키텍쳐&CI/CD

#125 feat: 액션 스크립트 수정, gitignore 수정, compose & .vscode 파일 삭제
  .github/workflows/deploy.yml
  .gitignore
  .vscode/settings.json
  README.md
  client/package-lock.json
  client/src/components/common/SectionTitle.jsx
  docker/docker-compose.yml
Labels: 🛠 fix, 아키텍쳐&CI/CD

#126 feat: 생성 시 유효성 검사 추가, custom-modal 컴포넌트, css detail 수정
  client/public/index.html
  client/src/App.tsx
  client/src/components/custom-alert/AlertModal.jsx
  client/src/components/header/header-components/HeaderMenu.jsx
  client/src/components/make-section/MakeSection.jsx
  client/src/components/make-section/make-section-components/InputTitle.jsx
  client/src/components/make-section/make-section-components/input-title-components/BoostCampId.jsx
  client/src/components/make-section/make-section-components/input-title-components/CreateBtn.jsx
  client/src/components/make-section/make-section-components/input-title-components/Generation.jsx
  client/src/components/make-section/make-section-components/input-title-components/style.js
  client/src/reducer/doc-data-reducer.ts
  client/src/resource/img/close.svg
Labels: 🪲 QBug, 🧑🏻‍💻 front, 🛠 fix

#131 feat: 문서 생성 페이지 유효성 검사, css 수정
  client/src/components/make-section/MakeSection.jsx
  client/src/components/make-section/make-section-components/InputTitle.jsx
  client/src/components/make-section/make-section-components/input-title-components/style.js
  client/src/components/select-modal/SelectModal.jsx
Labels: 🧑🏻‍💻 front

#134 feat: JWT를 이용한 로그인 구현
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/components/join-section/JoinSection.jsx
  client/src/components/login-section/LoginSection.jsx
  client/src/components/main-door/MainDoor.jsx
  client/src/event-handler/select-handler.ts
  client/src/pages/GithubCallbackPage.jsx
  client/src/pages/JoinPage.jsx
  client/src/pages/LoginPage.jsx
  client/src/pages/SearchPage.jsx
  client/src/utils/login.js
  server/.eslintrc.js
  server/package-lock.json
  server/package.json
  server/src/api/auth.ts
  server/src/api/index.ts
  server/src/api/middleware.ts
  server/src/config/index.ts
  server/src/services/login.ts
  server/src/services/util.ts
  server/src/sql/documents-query.ts
  server/src/sql/users-query.ts
  server/src/types/apiInterface.ts
  server/src/types/d.ts
  server/tsconfig.json
Labels: 🧑🏻‍💻 front, 👨🏻‍💻 backend

#142 chore: 배포 서버, 도커 파일 gitignore 적용
  .gitignore
  client/package-lock.json
  docker/nginx/nginx/conf.d/default.conf
Labels: 아키텍쳐&CI/CD

#137 feat, refactor : 본문 이미지 추가 버튼 구현, 이미지 최적화 진행
  client/package-lock.json
  client/package.json
  client/src/components/common/MdParser.jsx
  client/src/components/make-section/make-section-components/ContentImgUploadBtn.jsx
  client/src/components/make-section/make-section-components/Editor.jsx
  client/src/components/make-section/make-section-components/EditorBox.jsx
  client/src/services/image-upload.js
  server/src/api/images.ts
Labels: 💫 chore, 🧑🏻‍💻 front

#140 feature: BE/FE classification 재정의 및 문서작성시 분류 테이블에 열 삽입
  client/src/App.tsx
  client/src/components/category-section/CategorySection.jsx
  client/src/components/main-door/MainDoor.jsx
  client/src/components/make-section/UpdateSection.jsx
  client/src/components/make-section/make-section-components/InputTitle.jsx
  client/src/components/make-section/make-section-components/input-title-components/BoostCampId.jsx
  client/src/components/make-section/make-section-components/input-title-components/Classification.jsx
  client/src/components/make-section/make-section-components/input-title-components/Generation.jsx
  client/src/components/wiki-section/WikiSection.jsx
  client/src/components/wiki-section/wiki-section-components/WikiCard.jsx
  client/src/components/wiki-section/wiki-section-components/WikiCategory.jsx
  client/src/pages/CategoryPage.jsx
  client/src/reducer/doc-data-reducer.ts
  client/src/resource/message/index.js
  client/src/resource/message/words.js
  client/src/utils/documents.js
  server/src/api/categories.ts
  server/src/api/documents.ts
  server/src/api/index.ts
  server/src/services/util.ts
  server/src/sql/classification-query.ts
  server/src/sql/documents-query.ts
  server/src/subscribers/document-subscriber.ts
  server/src/types/apiInterface.ts
Labels: 💫 chore, 🧑🏻‍💻 front, 👨🏻‍💻 backend

#143 Bugfix/cicd fix j038
  .gitignore
  client/.env.example
  client/package-lock.json
  client/src/pages/GithubCallbackPage.jsx
  docker/nginx/nginx/conf.d/default.conf
  docker/nginx/nginx/nginx.conf
  server/.env.example
Labels: 🛠 fix

#144 feat: 회원가입 페이지 구현
  .gitignore
  client/src/components/join-section/JoinSection.jsx
  client/src/components/join-section/join-section-components/Agreement.jsx
  client/src/components/join-section/join-section-components/AgreementButton.jsx
  client/src/components/join-section/join-section-components/AgreementCheckbox.jsx
  client/src/components/join-section/join-section-components/AgreementContent.jsx
  server/src/api/auth.ts
Labels: 🧑🏻‍💻 front

#149 feat : 분류페이지 구현
  client/src/components/category-section/CategorySection.jsx
  client/src/components/category-section/style.jsx
  client/src/components/search-section/SearchSection.jsx
  client/src/components/search-section/search-section-components/ResultFooter.jsx
  client/src/components/search-section/search-section-components/ResultView.jsx
  server/src/api/categories.ts
  server/src/api/documents.ts
  server/src/sql/classification-query.ts
Labels: 🧑🏻‍💻 front, 👨🏻‍💻 backend

#151 feat: 문서 작성 및 디자인 고도화 작업
  client/src/components/common/MainSection.jsx
  client/src/components/common/MdParser.jsx
  client/src/components/common/SectionTitle.jsx
  client/src/components/header/Header.jsx
  client/src/components/header/header-components/HeaderMenu.jsx
  client/src/components/header/header-components/HeaderSearchBar.jsx
  client/src/components/make-section/MakeSection.jsx
  client/src/components/make-section/UpdateSection.jsx
  client/src/components/make-section/make-section-components/DocCard.jsx
  client/src/components/make-section/make-section-components/Editor.jsx
  client/src/components/make-section/make-section-components/EditorWithPreview.jsx
  client/src/components/make-section/make-section-components/InputTitle.jsx
  client/src/components/make-section/make-section-components/TitleGuide.jsx
  client/src/components/make-section/make-section-components/input-title-components/BoostCampId.jsx
  client/src/components/make-section/make-section-components/input-title-components/CreateBtn.jsx
  client/src/components/make-section/make-section-components/input-title-components/DocName.jsx
  client/src/components/make-section/make-section-components/input-title-components/style.js
  client/src/components/side-section/SideSection.jsx
  client/src/components/wiki-section/WikiSection.jsx
  client/src/resource/img/bold-icon.svg
  client/src/resource/img/edit.png
  client/src/resource/img/image-upload-icon.svg
  client/src/resource/img/italic-icon.svg
  client/src/resource/img/rank-page.svg
  client/src/resource/img/text-line-icon.svg
  client/src/resource/img/total-page.svg
  client/src/resource/img/write-page.svg
  client/src/utils/display-width.ts
Labels: 🧑🏻‍💻 front, 🛠 fix

#153 feat: 에디터 꾸밈 효과 버튼 구현
  client/src/components/make-section/make-section-components/ContentEditIcon.jsx
  client/src/components/make-section/make-section-components/ContentImgUploadBtn.jsx
  client/src/components/make-section/make-section-components/EditorBox.jsx
  client/src/components/make-section/make-section-components/EditorWithPreview.jsx
Labels: 🧑🏻‍💻 front

#154 feature : 문서 동시성 검사 및 라우팅 주소와 관련하여 에러 라우팅 처리
  client/src/components/make-section/MakeSection.jsx
  client/src/components/make-section/UpdateSection.jsx
  client/src/components/search-section/SearchSection.jsx
  client/src/components/wiki-section/WikiSection.jsx
  client/src/pages/ErrorPage.jsx
  client/src/pages/WikiPage.jsx
  server/src/api/documents.ts
  server/src/sql/documents-query.ts
  server/src/types/apiInterface.ts
Labels: 🧑🏻‍💻 front, 👨🏻‍💻 backend

#152 feat: 권한 관련 로직 작업 완료
  client/package-lock.json
  client/package.json
  client/src/components/header/header-components/HeaderUser.jsx
  client/src/components/join-section/join-section-components/AgreementButton.jsx
  client/src/components/login-section/LoginSection.jsx
  client/src/components/make-section/MakeSection.jsx
  client/src/components/make-section/UpdateSection.jsx
  client/src/event-handler/select-handler.ts
  client/src/pages/GithubCallbackPage.jsx
  client/src/pages/JoinPage.jsx
  client/src/pages/MainPage.jsx
  client/src/pages/MakePage.jsx
  client/src/pages/UpdatePage.jsx
  client/src/services/image-upload.js
  client/src/styles/scss/CallbackPage.module.scss
  client/src/utils/login.js
  server/src/api/auth.ts
  server/src/api/documents.ts
  server/src/api/images.ts
  server/src/api/middleware.ts
Labels: 🧑🏻‍💻 front, 👨🏻‍💻 backend

#157 chore: Readme 수정
  README.md
Labels: 💫 chore

#159 fix: 15분 이상 로그인 시 로그인 관련 에러 버그 수정
  client/src/utils/login.js
  server/src/api/documents.ts
  server/src/services/login.ts
  server/src/services/util.ts
  server/src/sql/documents-query.ts
  server/src/types/apiInterface.ts
Labels: 👨🏻‍💻 backend, 🛠 fix

#161 feat: style 디테일 수정, MBTI 순위 페이지 구현
  client/src/App.tsx
  client/src/components/common/MainSection.jsx
  client/src/components/header/header-components/HeaderMenu.jsx
  client/src/components/join-section/join-section-components/Agreement.jsx
  client/src/components/login-section/LoginSection.jsx
  client/src/components/rank-section/RankSection.jsx
  client/src/components/rank-section/rank-components/MbtiRank.jsx
  client/src/components/rank-section/rank-components/mbti-list-component/MbtiCircle.jsx
  client/src/components/rank-section/rank-components/mbti-list-component/MbtiList.jsx
  client/src/components/rank-section/rank-components/style.ts
  client/src/components/search-section/search-section-components/ResultFooter.jsx
  client/src/pages/RankPage.jsx
  client/src/resource/img/github-white.png
  server/src/api/index.ts
  server/src/api/rank.ts
  server/src/sql/rank-query.ts
Labels: 🧑🏻‍💻 front, 👨🏻‍💻 backend

#160 feat : 전체페이지 구현
  client/src/App.tsx
  client/src/components/header/header-components/HeaderMenu.jsx
  client/src/components/make-section/MakeSection.jsx
  client/src/components/make-section/UpdateSection.jsx
  client/src/components/total-documents-section/TotalDocumentsSection.jsx
  client/src/components/total-documents-section/style.jsx
  client/src/components/wiki-section/WikiSection.jsx
  client/src/pages/TotalDocumentsPage.jsx
  client/src/pages/WikiPage.jsx
  client/src/utils/ip-check.js
  server/src/api/categories.ts
  server/src/api/documents.ts
  server/src/services/util.ts
  server/src/services/words.ts
  server/src/sql/classification-query.ts
  server/src/sql/documents-query.ts
Labels: 🧑🏻‍💻 front, 👨🏻‍💻 backend, 🛠 fix
